Repository Classicler/GodotAlgoExperiments, pull requests merged in 2020-12, with the labels that each got.

#1 More Organized Version of the Repository
  Lora-Bold - Copy.ttf
  README.md
  docs/LICENSE
  docs/SECURITY.md
  docs/UPDATES.md
  src/Algorithms/Shunting Yard/Shunting Yard Algorithm exp.gd
  src/Algorithms/Shunting Yard/Shunting Yard Algorithm exp.tscn
  src/Fonts/Lora/LoraBold_25.tres
  src/Fonts/Lora/LoraBold_30.tres
  src/project.godot
Labels: enhancement

#3 Add documents
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  UPDATES.md
Labels: enhancement

#4 1.0.1.0
  CHANGELOG.md
  README.md
  UPDATES.md
  src/Algorithms/Shunting Yard/Shunting Yard Algorithm exp.gd
Labels: bug, documentation

#6 1.0.2 ready
  README.md
  src/icon.png
Labels: bug
